### PR TITLE
Additional ECS Capture Examples

### PR DESCRIPTION
**Pull request by ukmadlz**
## Why
Edge cases where the `ecs` capture endpoint is silently failing on certain objects sent from the SDKs

## What
Additional example files to run testing against

## Validation
* [ ] CI passes
* [ ] Verified in staging
* etc...

### CODE REVIEW

**Comment by LouManglass** [comment]
@devdoshi happy to learn more about this, but I think you're going to be the better reviewer here.

**Comment by devdoshi** [comment]
@LouManglass I had to fix some things since the snapshots weren't updated and weren't stably identified, but if CI passes then this is good to merge

**Review by devdoshi — APPROVED** [review]
approved if tests pass

**Comment by LouManglass** [comment]
Woo!

**Pull request merged**
