### PR TITLE
added key component to response descriptions

### PR DESCRIPTION
**Pull request by trulyronak**
Fixed issue where changing response descriptions appeared to not make any changes

the issue was that react wasn't updating the components. since Response Descriptions were mapped via `ContentTabs`, it needed a `key` component in order to trigger an update when the props changed

also in this pr
- added `different-responses.json` to test this fix
- updated `yarn.lock`

### CODE REVIEW

**Comment by devdoshi** [comment]
Nice work!

**Comment by devdoshi** [comment]
Looks like you're taking a look at the other usages of the component for the same issue - awesome!

**Comment by trulyronak** [comment]
modified it to use a key for all things for ContentTab - i’m not 100% if this is the best key - right now I'm combining the `contentTypeTab`, `responseStatusCode,` and `responseContentType` to create a key for each one, but if there's a uuid field I'm missing that would be much better

**Comment by acunniffe** [comment]
Seems like a fine place to me! nice work sir. Merging now

**Pull request merged**
