### PR TITLE
Add cloud viewer tag on release instead of master

### PR DESCRIPTION
**Pull request by niclim**
## Why
Describe the motivation for the changes.

It doesn't look like cloudviewer is getting deployed. I'm not 100% sure i follow the deployment pipeline - but I think that this fix should deploy the latest version of cloud viewer

This targets release (and I'll merge this back into develop)

## What
What's changing? Anything of note to call out?

## Validation
* [ ] CI passes
* [ ] Verified in staging
* etc...

### CODE REVIEW

**Comment by niclim** [comment]
As an aside, we should fix the regression build errors in the test regression scenarios

**Comment by notnmeyer** [comment]
this workflow doesn’t deploy anything. it just pushes a docker image to our registry. historically, i have been against allowing this repo access to k8s

 i’m afk at the moment so cant refresh my memory on deploying it, but let’s plan on following up either later today or monday and we’ll sort it out.

**Comment by niclim** [comment]
Ah ok - I'll close this Pr since this is not the correct fix - and lets follow up later today

**Review by LouManglass — APPROVED** [review]
This makes sense, as does the merge flow you suggested. I'd wait for Nate's eyes, but it seems sensible based on what I read.

**Pull request closed without merging**
