### PR TITLE
Run End to End Tests before Release

### PR DESCRIPTION
**Pull request by trulyronak**
This runs optic's end-to-end tests before any release, blocking release if they do not pass.

Before merging, note that will require a new org secret — a repo access token for end-to-end tests, called `END_TO_END_ACCESS_KEY`

### CODE REVIEW

**Comment by trulyronak** [comment]
Note — it's currently not succeeding (https://github.com/trulyronak/optic/runs/879648850?check_suite_focus=true)

**Comment by acunniffe** [comment]
@trulyronak  what's required to put this over the edge? Nice work

**Comment by trulyronak** [comment]
Currently just trying to get the tests to pass — as of now it seems to be running into Docker / port issues, I'm working with @devdoshi to figure it out

**Comment by trulyronak** [comment]
It's in a functional state now (thanks to @devdoshi for helping me getting it to run), but it looks like it's still failing some tests — https://github.com/trulyronak/optic/runs/882855790?check_suite_focus=true

**Comment by acunniffe** [comment]
@devdoshi @trulyronak I updated the tests to skip the failing one, but things seem to be in a weird state with the PR. In the check I'm getting 'can't find token' and the source of the PR says 'unknown repository'

**Comment by trulyronak** [comment]
Oh yes — I was running it on my repo until this stage — we'll need a secret called `END_TO_END_ACCESS_KEY` which is a repository access token for the end-to-end test repo

**Comment by trulyronak** [comment]
Closing this in favor of #291 - I accidentally deleted the fork that held this code, so I moved it over to a branch

**Pull request closed without merging**
