### PR TITLE
Prepare the build and publishing of Optic v8

### PR DESCRIPTION
**Pull request by devdoshi**
You can test the build and publish process by

(make sure you clone the branch fresh so there are no cached modules/artifacts)
-  $ yarn install
-  $ yarn run build-domain
-  $ yarn wsrun --stages --report --fast-exit ws:build

(make sure docker is running)
-  $ source export_development_aliases.sh
-  $ publish-optic-locally
-  $ install-optic-from-local-registry

Then use the `api` binary as you would normally

### CODE REVIEW

**Comment by JaapRood** [comment]
Followed the instructions against a fresh clone of this branch, all good up to `$ yarn wsrun --stages --report --fast-exit ws:build`:

```
@useoptic/cli-client
 | 16:14:43 - Projects in this build:
 |     * tsconfig.json
 |
@useoptic/cli-config
 | 16:14:43 - Projects in this build:
 |     * tsconfig.json
 |
 | 16:14:43 - Project 'tsconfig.json' is out of date because output file 'build/index.js' does not exist
 |
@useoptic/cli-client
 | 16:14:43 - Project 'tsconfig.json' is out of date because output file 'build/client.js' does not exist
 |
@useoptic/cli-config
 | 16:14:43 - Building project '/Users/jaaprood/Sites/optic/optic-publish-test/workspaces/cli-config/tsconfig.json'...
 |
@useoptic/cli-client
 | 16:14:43 - Building project '/Users/jaaprood/Sites/optic/optic-publish-test/workspaces/cli-client/tsconfig.json'...
 |
 | src/client.ts(2,38): error TS2307: Cannot find module '@useoptic/cli-config'.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 | `yarn ws:build` failed with exit code 1
Stopping 3 active children

Report:
  1 packages finished `ws:build` with error: @useoptic/cli-client
  1 packages finished `ws:build` successfully: @useoptic/cli-config
  1 packages have been cancelled running `ws:build`: @useoptic/domain
  4 packages have not started running `ws:build`: @useoptic/proxy, @useoptic/ui, @useoptic/cli-server, @useoptic/cli

Aborted execution due to previous error
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Weird, because the symlinks for workspaces do seem to be in place:

```
$ tree node_modules/@useoptic/
node_modules/@useoptic/
├── cli -> ../../workspaces/local-cli
├── cli-client -> ../../workspaces/cli-client
├── cli-config -> ../../workspaces/cli-config
├── cli-server -> ../../workspaces/cli-server
├── domain -> ../../workspaces/domain
├── proxy -> ../../workspaces/proxy
└── ui -> ../../workspaces/ui
```

**Comment by devdoshi** [comment]
I'll take a look in a few minutes

**Comment by JaapRood** [comment]
I managed to get things running by using `yarn postpull`. It's less concise, but seems to have installed things correctly, with ultimately `$ install-optic-from-local-registry` completing successfully. However, as I already had optic installed globally, `which api` still pointed to the one globally installed v7. Once I removed that at `which api` points at nothing, the `install-optic-from-local-registry` produces errors about not being able to find packages. Here's a sample (there's more):

```
Error: Couldn't find package "has-values@^1.0.0" required by "has-value@^1.0.0" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/local/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:36528:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/lib/node_modules/yarn/lib/cli.js:304:30)
    at /usr/local/lib/node_modules/yarn/lib/cli.js:317:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "has-values@^0.1.4" required by "has-value@^0.3.1" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/local/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:36528:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/lib/node_modules/yarn/lib/cli.js:304:30)
    at /usr/local/lib/node_modules/yarn/lib/cli.js:317:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "object-copy@^0.1.0" required by "static-extend@^0.1.1" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/local/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:36528:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/lib/node_modules/yarn/lib/cli.js:304:30)
    at /usr/local/lib/node_modules/yarn/lib/cli.js:317:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by devdoshi** [comment]
Hmm the original error is because cli-client did not list cli-config in its dependencies. I fixed that locally and it looks good now. How did you verify that the binary was pointing to the v7 as opposed to v8? If you install from the local registry and then remove it from your computer and then attempt to install again without republishing to the local I'm not sure what will happen. But seems like some mismatch between yarn state when using the local registry vs subsequently using what's on your computer outside of the local registry

**Comment by JaapRood** [comment]
> How did you verify that the binary was pointing to the v7 as opposed to v8?

By running `which api`, which pointed to the globally installed version:

```
$ which api
/Users/jaaprood/.nvm/versions/node/v12.16.1/bin/api
```

And verified through:

```
$ api -v
@useoptic/cli/7.0.10 darwin-x64 node-v12.16.1
```

I'll get the changes you pushed a go.

**Comment by devdoshi** [comment]
```
alias publish-optic-locally="cd $OPTIC_SRC_DIR && yarn run registry:clean-optic && yarn run registry:start-background && yarn run publish-local"
alias install-optic-from-local-registry="YARN_REGISTRY=http://localhost:4873 yarn global add @useoptic/cli --registry=http://localhost:4873"
```

If you run those two commands in order then you should definitely end up with optic 8 installed globally. Let me know how it goes!

**Comment by JaapRood** [comment]
Everything up to `install-optic-from-local-registry` went smoothly this time. Either it's incredibly bad luck, but as soon as I run that, my Macbook becomes real spotty with it's internet connection (wifi stable), resulting in a bunch of errors about not being able to install packages. I've also spotted 404s in the output, where I would expect 5xx for a failed connection.

I think someone else will have to play QA on this!

**Comment by devdoshi** [comment]
Ok no worries. I should note that if you are clearing the environment every time, the local registry is going to proxy all the non @useoptic/* module requests through to npm so that's probably where it's being flaky. If you don't clear the local registry state then it should be able to install everything easily. So if you're going to be running it a few times, it might make sense to start the local registry elsewhere and skip the command that starts it. The sequence above assumes that it's just going to run once on a clean slate like in CI

**Comment by acunniffe** [comment]
I wasn't able to get this to install the binary @devdoshi

**Pull request merged**
