### PR TITLE
Batch of OAS fixes

### PR DESCRIPTION
**Pull request by acunniffe**
## 🍗 Description

- clear traffic captures after `--document` or `--patch` 
- Restore system proxy settings if already set 
- NaN fix

## 📚 References
_Links to relevant docs (Notion, Twist, GH issues, etc.), if applicable._

## 👹 QA
_How can other humans verify that this PR is correct?_

### CODE REVIEW

**Comment by acunniffe** [comment]
@notnmeyer if you wanted to try this w/ your proxy setup that'd be great. I made some fake ones and it worked, but not a real world

**Review by niclim — APPROVED** [review]

**Comment by notnmeyer** [comment]
> your proxy setup that'd be great

i don't have a proxy set up. im just entering arbitrary values in the network settings and checking them before and after a capture sessions.


this doesn't seem to work for me. i enabled an http proxy with a random port, then started a capture session, and then ctrl-c'd,

```
➜ OPTIC_TELEMETRY_LEVEL=off yarn local:run oas capture ~/code/optic-ci-testing/openapi.yaml https://google.com
Password:
 » Proxy running on https://localhost:8000. System proxy updated
 help  Press [ Enter ] to finish capturing requests
ℹ No requests captured
 ✓ Wrote har traffic to /tmp/optic/captures/a73d0f4e4019ec1162bcd4e4d2e8a194/1675695906698.har
exec error: Error: Command failed: networksetup -setwebproxystate "Thunderbolt Ethernet Slot 0" 127.0.0.1 8000 off
```

its failing to reset the proxy settings. its also swallowing the error coming from networksetup,

```
➜ networksetup -setwebproxystate "Thunderbolt Ethernet Slot 0" 127.0.0.1 8000 off
** Error: The parameters were not valid.
```

**Comment by notnmeyer** [comment]
also, i don't think there's anything here to handle authenticated proxies (like restoring the user/pass). seems like we'd still break that configuration.

**Review by notnmeyer — CHANGES_REQUESTED** [review]
elaborated in other comments

**Pull request merged**
