### PR TITLE
Upstream sync from `opticdev/monorail`

### PR DESCRIPTION
**Pull request by opticbot**
This PR was created automatically from https://github.com/opticdev/monorail/commit/2f2d2b40dc6dc132f02377fd6b2ba49e0af80a29

### CODE REVIEW

**Review by JaapRood — DISMISSED** [review]

**Comment by niclim** [comment]
@nalanj i think the diff integration test doesn't work with the synced repo

**Comment by nalanj** [comment]
Sync didn't move the new tmp folder over, so I just manually committed it for now.

**Comment by nalanj** [comment]
@JaapRood all set now

**Review by JaapRood — APPROVED** [review]
Thanks for resolving that @nalanj and @niclim :)

**Pull request merged**
