### PR TITLE
Add api url

### PR DESCRIPTION
**Pull request by nalanj**
## 🍗 Description
_What does this PR do? Anything folks should know?_

Adds a new `add-api-url` command to Optic that will simply take in an API URL and add it to the given spec file.

## 📚 References
_Links to relevant docs (Notion, Twist, GH issues, etc.), if applicable._

## 👹 QA
_How can other humans verify that this PR is correct?_

### CODE REVIEW

**Review by niclim — APPROVED** [review]
Do you think this should go on `api` instead of `spec`? I'm not sure where this would fit with our current distinctions

**Comment by nalanj** [comment]
@niclim I just figured it goes under spec because it touches on an individual spec file rather than touching a whole api. I'm not sure what the distinction between spec or api for us is.

**Comment by nalanj** [comment]
@niclim merge or should we talk to @acunniffe about where it goes?

**Comment by acunniffe** [comment]
I feel like this is better as a "add --no-verify" flag or something like that. Is the intent that this doesn't try to upload, but will make an API in optic cloud?

**Comment by nalanj** [comment]
@acunniffe No. It's just for marking up the spec with the x-optic-url. It comes up if you're doing things like updating a public spec in a job or are generating a spec and need to add the url to the file without it being added to the cloud since it's already there.

**Comment by niclim** [comment]
I think it's fine to just throw in spec for now, I don't think we have a strong distinction between API or spec right now, and since we think it's not a common use case we can throw it in, and then just alias it later

**Pull request merged**
