### PR TITLE
pull request template

### PR DESCRIPTION
**Pull request by notnmeyer**
adds a PR template.  kept it simple to get the conversation rolling. all feedback welcome.

### CODE REVIEW

**Comment by devdoshi** [comment]
just previewing here:

## Why
Describe the motivation for the changes.

## What
What's changing? Anything of note to call out?

## Validation
* [ ] CI passes
* [ ] Verified in staging
* etc...

**Review by devdoshi — APPROVED** [review]
Looks good to me, we can evolve the wording and initial state over time as we see fit

**Comment by notnmeyer** [comment]
maybe it makes sense to have the `what` section first?

**Review by JaapRood — APPROVED** [review]
Seems like a simple enough place to start :)

**Review by LouManglass — APPROVED** [review]

**Comment by acunniffe** [comment]
I like it, and I had no idea you could make checkboxes that check!

**Pull request merged**
