### PR TITLE
Fix/busted diff engine build

### PR DESCRIPTION
**Pull request by notnmeyer**
## Why
diff-engine builds are broken on the latest stable rust,

```
Error:  --> workspaces/diff-engine/src/protos/generated/shapehash.rs:9:4
  |
  | #![rustfmt::skip]
  |    ^^^^^^^^^^^^^
  |
  = note: `#[deny(soft_unstable)]` on by default
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
  = note: for more information, see issue #64266 <https://github.com/rust-lang/rust/issues/64266>
```

## What
Updates protobuff, and fixes a subsequent warning produced by the upgrade

## Validation
* [ ] CI passes

### CODE REVIEW

**Comment by jshearer** [comment]
I think you need to also regenerate the file that had the issue in it, right? Not sure how to do that

**Comment by jshearer** [comment]
Oh, it goes through a `build.rs` file, maybe it'll happen automatically...

**Comment by notnmeyer** [comment]
the generated files are gitignored. building locally produced a modified file 👍

**Review by jshearer — APPROVED** [review]
Looks like this fixed it!

**Review by devdoshi — APPROVED** [review]

**Pull request merged**
